document.write( '<nav class=\"navbar navbar-expand-lg navbar-dark bg-dark fixed-top\">\n' );
document.write( '<button class=\"navbar-toggler\" type=\"button\" data-toggle=\"collapse\" data-target=\"#navbarNavAltMarkup\" aria-controls=\"navbarNavAltMarkup\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">\n' );
document.write( '<span class=\"navbar-toggler-icon\"></span>\n' );
document.write( '</button>\n' );
document.write( '<div class=\"collapse navbar-collapse\" id=\"navbarNavAltMarkup\">\n' );
document.write( '<div class=\"navbar-nav\">\n' );
document.write( '<a class=\"nav-item nav-link\" href=\"apiPage.html\">API</a>\n' );
//document.write( '<a class=\"nav-item nav-link\" href=\"preference_script.html\">基本流程自動化</a>\n' );
document.write( '<a class=\"nav-item nav-link\" href=\"scriptPage.html\">掛機</a>\n' );
//document.write( '<a class=\"nav-item nav-link\" href=\"settingPage.html\">設定</a>\n' );
document.writeln("<li class=\"nav-item dropdown\">");
document.writeln("<a class=\"nav-link dropdown-toggle\" href=\"#\" id=\"navbarDropdown\" role=\"button\" data-toggle=\"dropdown\" aria-haspopup=\"true\" aria-expanded=\"false\">");
document.writeln("設定");
document.writeln("</a>");
document.writeln("<div class=\"dropdown-menu\" aria-labelledby=\"navbarDropdown\">");
document.writeln("<a class=\"dropdown-item\" href=\"gameSetting.html\">遊戲</a>");
document.writeln("<a class=\"dropdown-item\" href=\"currencySetting.html\">幣別</a>");
document.writeln("<a class=\"dropdown-item\" href=\"languageSetting.html\">語系</a>");
document.writeln("<div class=\"dropdown-divider\"></div>");
document.writeln("<a class=\"dropdown-item\" href=\"scriptSetting.html\">腳本</a>");
document.writeln("<div class=\"dropdown-divider\"></div>");
document.writeln("<a class=\"dropdown-item\" href=\"pathSetting.html#\">路徑設定</a>");
document.writeln("</div>");
document.writeln("</li>");
document.write( '</div>\n' );
document.write( '</div>\n' );
document.write( '</nav>' );
